### PR TITLE
JUnit v4.13.1

### PR DESCRIPTION
**Pull request by nhojpatrick**
Upgrade to JUnit v4.13.1

### CODE REVIEW

**Comment by garydgregory** [comment]
You don't need to submit PRs for version changes, Dependabot already does this.

**Comment by nhojpatrick** [comment]
@garydgregory i thought dependabot got disabled as everyone was complaining about the huge number of emails they were getting.

I've done the same pr for all commons project as some were not on 4.13, so upgraded from the earlier version toos.

**Comment by melloware** [comment]
I haven't quite figured out Dependabot yet as 1 of my projects it sent a PR for Junit but for another project it didn't send the PR until a few days later.

**Comment by melloware** [comment]
I think this is safe to close as this just appeared today: https://github.com/apache/commons-beanutils/pull/44

**Pull request closed without merging**
