### PR TITLE
BEANUTILS-539/BEANUTILS-509: Switch WeakFastHashMap for ConcurrentWeakHashMap

### PR DESCRIPTION
**Pull request by melloware**
Gave attribution to original authors and the original code has this disclaimer:

_Written by Doug Lea with assistance from members of JCP JSR-166
Expert Group and released to the public domain, as explained at_
http://creativecommons.org/licenses/publicdomain

All unit tests passing.

### CODE REVIEW

**Comment by XenoAmess** [comment]
Hi. why this clised？

**Comment by melloware** [comment]
Open for over 3 years. No activity. I am tired of fixing conflicts. So I closed it let someone else reopen it.

**Comment by XenoAmess** [comment]
@garydgregory any time for review it pls？I think this refinition critical...

**Comment by garydgregory** [comment]
> @garydgregory any time for review it pls？I think this refinition critical...

I'll take a look tonight or tomorrow.

**Pull request closed without merging**
