### PR TITLE
[BEANUTILS-509] Wrap WeakHashMap in Collections.synchronizedMap

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by melloware** [comment]
@garydgregory any chance of a Beanutils2 release anytime soon?  I think it just needs  the whole codebase to be formatted and i think its worthy of a release.

**Comment by garydgregory** [comment]
There are a few more clean ups IIRC, I will try to take a look over the weekend.

**Comment by melloware** [comment]
Thank you very much.

**Comment by garydgregory** [comment]
What are the performance consequences of this PR?

**Comment by melloware** [comment]
No idea if there is a perfomance measurement suite I was just reading the ticket and it seems the Jenkins team definitely has this bug and use case.  You are more than welcome to reject this PR.

**Comment by melloware** [comment]
@garydgregory Just pinging you again about a potential BeanUtils2 release?

**Comment by melloware** [comment]
Closing this PR in favor of #37

**Pull request closed without merging**
