### PR TITLE
BEANUTILS-539/BEANUTILS-509: Switch WeakFastHashMap for ConcurrentWeakKeyHashMap

### PR DESCRIPTION
**Pull request by melloware**
Gave attribution to original authors and the original code has this disclaimer:

_Written by Doug Lea with assistance from members of JCP JSR-166
Expert Group and released to the public domain, as explained at_
http://creativecommons.org/licenses/publicdomain

All unit tests passing.

### CODE REVIEW

**Comment by melloware** [comment]
I am also happy to remove the original @author tags as well?

**Comment by XenoAmess** [comment]
Hi.
Looks good to me.
But:
1. Is it leagle to use it like this? should we have to add Doug Lea's name to some additional places? I'm not quite familiar with apache 2 license/legal problem, but maybe better to let @garydgregory re-check this.
2. <tt> is used in the new added codes and which is not supported by the current configuration of javadoc-plugin.
please consider about change <tt> to <code> or something else, or modify the configuration.

**Comment by melloware** [comment]
Fixed the `<tt>` to `<code>` thanks for that.  As for the legality waiting for @garydgregory to chime in but the fact the code states its public domain feels pretty safe to me..
```
Written by Doug Lea with assistance from members of JCP JSR-166
Expert Group and released to the public domain, as explained at
http://creativecommons.org/licenses/publicdomain
```

**Comment by melloware** [comment]
Closing this PR for a new one.

**Comment by bitwiseman** [comment]
The new PR is #56 ?

**Comment by melloware** [comment]
Yes that is correct.

**Comment by melloware** [comment]
I have a version of Commons Beanutils published using this PR.

```xml
<dependency>
  <groupId>com.melloware</groupId>
  <artifactId>commons-beanutils2</artifactId>
  <version>2.0.0</version>
</dependency>
```

**Comment by bitwiseman** [comment]
@melloware Do you have it back ported to 1.x?

**Comment by melloware** [comment]
Nope.

**Pull request closed without merging**
