### PR TITLE
BEANUTILS-541 - FluentPropertyBeanIntrospector caches corrupted writeMethod (1.x backport)

### PR DESCRIPTION
**Pull request by seregamorph**
https://issues.apache.org/jira/browse/BEANUTILS-541

Backport #68 for 1.x

### CODE REVIEW

**Comment by seregamorph** [comment]
@garydgregory I see that you have some activity in this project. WDYT finally review real issues with value? I mean these two:
* https://github.com/apache/commons-beanutils/pull/69
* https://github.com/apache/commons-beanutils/pull/68

Current implementation has a severe issue. If you think this project does not deserve meaningful changes, please let me know so I would not waste time on these efforts.

**Comment by garydgregory** [comment]
Hello @seregamorph 
Thank you for the reminder, please rebase on git master to pick up the new GH workflow.

**Comment by seregamorph** [comment]
The branch is rebased. Please note this this change is just a backport of
https://github.com/apache/commons-beanutils/pull/68

**Comment by basil** [comment]
@seregamorph #68 was merged to the `master` branch but apparently introduced a concurrency issue which was fixed in #234 on the `master` branch. #69 (a backport of #68) was then merged to the `1.X` branch, but no backport of #234 was ever merged to the `1.X` branch. 1.10.0 was then released from the `1.X` line. Does this mean that the 1.10.0 release is subject to the concurrency issue that was fixed in #234 on the `master` branch?

**Comment by seregamorph** [comment]
@basil it seems that I've forgotten to backport the concurrency fix to `1.x`. It means that we need a hotfix for `1.10.0` cherry-picking https://github.com/apache/commons-beanutils/pull/234

**Comment by garydgregory** [comment]
Hello @seregamorph 
Feel free to create a PR and I can cut another release candidate later this week or next. Cherry-picking won't work since the package names are different. 
TY!

**Comment by seregamorph** [comment]
@garydgregory https://github.com/apache/commons-beanutils/pull/325
@basil thanks for finding this (and apologies for my mistake), also please take a look at the fix (and verify if you have opportunity)

**Pull request merged**
